### ISSUE TITLE
Ethic bonuses and penalties

### ISSUE THREAD

**Issue by TheStoryEnthusiast** [dan3401/Story-Makes-a-Mod-Pack-#11]
Go through them and round up all effects to the nearest percent, since Stellaris doesn't recognize modifiers smaller than a percent if it's coming from an ethic.
Idk just fix it.

**Comment by dan3401** [comment]
also have a balence pass on them at the same time to encourage picking different ones

**Comment by TheStoryEnthusiast** [comment]
All done! Fanatic industrialist is a little weaker (habitability penalty from 7.5% to 10%) and materialist is a little stronger (research bonuses from 7.5% to 10%)
