### ISSUE TITLE
Integrate "Few New Origins"

### ISSUE THREAD

**Issue by TheStoryEnthusiast** [dan3401/Story-Makes-a-Mod-Pack-#23]
- [x] Download it [here](https://steamcommunity.com/sharedfiles/filedetails/?id=2040796138)
- [x] Copy all files into a secondary location
- [x] Edit the copied files so they'll play nice with the rest of the mod-pack
- [x] Move the files into the mod-pack

Integrating new mods will be VERY TOUGH now that we can't use Irony to just do it for us (if you're not sure why we can't use Irony, message me).

**Comment by lyratcm** [comment]
I will deal with this one so as not to waste others time for something i wanted

**Comment by lyratcm** [comment]
pretty sure everything was integrated correctly (most of them didn't overlap)

**Comment by lyratcm** [comment]
Remove infector  spawn due to it being too similar

**Comment by TheStoryEnthusiast** [comment]
Yeah, I do NOT want more origins added to the already immense list if we already have something similar to it.

**Comment by lyratcm** [comment]
done
