### ISSUE TITLE
Policy "Refugees" becomes invalid?

### ISSUE THREAD

**Issue by TheStoryEnthusiast** [dan3401/Story-Makes-a-Mod-Pack-#25]
![asdf](https://cdn.discordapp.com/attachments/815375116212633661/816484265738764358/Screen_Shot_2021-03-02_at_5.12.24_PM.png)
With this build, suddenly none of the options for the Refugees policy become selectable.

**Comment by lyratcm** [comment]
#59 is similar will take a look

**Comment by lyratcm** [comment]
this and #59 are fixed, removed the requirement to have met someone
