### ISSUE TITLE
FUCK zero-economy strats

### ISSUE THREAD

**Issue by TheStoryEnthusiast** [dan3401/Story-Makes-a-Mod-Pack-#38]
Let's reduce ALL job output by 50% when running on bingo energy instead of a 50% penalty to minerals from jobs.
Maybe also apply a 25% penalty to all job output when running bingo minerals?

**Comment by lyratcm** [comment]
done, also moved assembally reductions to comes from alloys rather than minerals to reflect changes to its costs
