### ISSUE TITLE
Trait "Living Architecture"/"Rooted" KILL IT WITH FIRE

### ISSUE THREAD

**Issue by TheStoryEnthusiast** [dan3401/Story-Makes-a-Mod-Pack-#54]
![asdf](https://i.kym-cdn.com/entries/icons/original/000/030/124/cast.jpg)

**Comment by lyratcm** [comment]
This is an amazing trait that doesn't need to be removed :)

**Comment by lyratcm** [comment]
fixed when dealing with #66
