### ISSUE TITLE
Origin "Infector Swarm" Needs Sorting Please

### ISSUE THREAD

**Issue by TheStoryEnthusiast** [dan3401/Story-Makes-a-Mod-Pack-#58]
Please keep all modded sorted below the vanilla origins. Thanks for understanding. I'm just really particular about projects I work on.

**Comment by lyratcm** [comment]
its the one thats been removed, i had sorted the other 2 and had though i sorted this one. didn't fix it straight away due to feedback from anton that it was too similar to other ones so was going to remove it anyway
