### ISSUE TITLE
Policy "Economic Stance" integrate with "Colleganza"

### ISSUE THREAD

**Issue by TheStoryEnthusiast** [dan3401/Story-Makes-a-Mod-Pack-#65]
Make the Colleganza trade policy activate both "Free Market" economic stance and "Planned" economic stance

**Comment by lyratcm** [comment]
Need locs for the policy flag
![image](https://user-images.githubusercontent.com/13206890/110793098-26904500-826c-11eb-97e8-73cdf8992423.png)
