### ISSUE TITLE
shipclass_military_build_cost_mult doesn't do anything

### ISSUE THREAD

**Issue by lyratcm** [dan3401/Story-Makes-a-Mod-Pack-#76]
![image](https://user-images.githubusercontent.com/13206890/111023957-f4015c00-83d3-11eb-8cde-a85b8ae5c80b.png)
Is meant to change the cost of military ships. (this is take from the supporters civic which has a +25% modifer)
have changed both instances of it to ship build cost until it can be inverstiaged

**Comment by TheStoryEnthusiast** [comment]
Tbh I was planning on overhauling that civic whenever I got the chance @dan3401 , unless you like the civic as-is, in which case I can make a new civic with the planned effects.

**Comment by lyratcm** [comment]
I was only using the civic as an example and hadn't actually used it, was testing out the fury road policy as the same bit of code is also there

**Comment by lyratcm** [comment]
forgot to close this. 
This haas been fixed where is appears but it is code whne used otherwise
