### ISSUE TITLE
Unselectable Megacorp Civics

### ISSUE THREAD

**Issue by TheStoryEnthusiast** [dan3401/Story-Makes-a-Mod-Pack-#82]
The following civics require ethics that are not possible to select under the "megacorp" authorities:

- [x] Employee Owned Co-op (requires Fanatic Egalitarian, which locks out all authorities except Democratics)
- [x] Heritage Trust (requires Fanatic Xenophobe, which locks out both megacorp authorities)
- [x] Investigation & Security Services (requires Fanatic Authoritarian, which locks out all authorities except Autocracies)

**Comment by lyratcm** [comment]
1) changed to egaliterian
2) changed to xenophobe
3) changed to authoritarian 
all has simple effects and were still in flavour so nothing more should be requried
